
[functions.auto-knowledge-harvester]
enabled = true
verify_jwt = true
import_map = "./functions/auto-knowledge-harvester/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/auto-knowledge-harvester/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/auto-knowledge-harvester/*.html" ]

[functions.chat-completion]
enabled = true
verify_jwt = true
import_map = "./functions/chat-completion/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chat-completion/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chat-completion/*.html" ]
